------------------------------------------------------
--Create User
CREATE USER cardealership
    IDENTIFIED BY Pa55word
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    QUOTA 10M ON users;

GRANT connect to cardealership;
GRANT resource to cardealership;
GRANT create session TO cardealership;
GRANT create table TO cardealership;
GRANT create view TO cardealership;

conn cardealership/Pa55word
------------------------------------------------------
--USER
CREATE TABLE USER_TBL(
USER_ID NUMBER PRIMARY KEY,
USER_USERNAME VARCHAR2(20),
USER_PASSWORD VARCHAR2(20),
USER_TYPE VARCHAR2(20)
);
--CAR TBL
CREATE TABLE CAR_TBL(
CAR_ID NUMBER PRIMARY KEY,
CAR_OWNER NUMBER,
CAR_MODEL VARCHAR2(20),
CAR_YEAR NUMBER,
CAR_COLOR VARCHAR(20),
CAR_PRICE NUMBER
);
--OFFER
CREATE TABLE OFFER_TBL(
OFFER_ID NUMBER PRIMARY KEY,
CAR_ID NUMBER,
USER_ID NUMBER,
OFFER_DOWNPAYMENT NUMBER,
OFFER_TERMLOANLENGTH NUMBER,
OFFER_STATUS VARCHAR2(20)
);
--CONTRACT
CREATE TABLE CONTRACT_TBL(
CONTRACT_ID NUMBER PRIMARY KEY,
OFFER_ID NUMBER
);
--PAYMENT TBL
CREATE TABLE PAYMENT_TBL(
PAYMENT_ID NUMBER PRIMARY KEY,
PAYMENT_VALUE NUMBER,
CONTRACT_ID NUMBER
);
-----------------------------------------------------------
--PROCEDURES
CREATE OR REPLACE PROCEDURE INSERTUSER
(USER_USERNAME VARCHAR2, USER_PASSWORD VARCHAR2)
AS
BEGIN
    INSERT INTO USER_TBL VALUES (USER_SEQ.NEXTVAL, USER_USERNAME,USER_PASSWORD,'Customer');
    COMMIT;
END;
/
CREATE OR REPLACE PROCEDURE INSERTCAR
(CAR_MODEL VARCHAR2, CAR_YEAR NUMBER, CAR_COLOR VARCHAR,CAR_PRICE NUMBER)
AS
BEGIN
    INSERT INTO CAR_TBL VALUES(CAR_SEQ.nextval,0, CAR_MODEL, CAR_YEAR, CAR_COLOR, CAR_PRICE);
    COMMIT;
END;
/
CREATE OR REPLACE PROCEDURE REMOVECAR
(THIS_CAR_ID NUMBER)
AS
BEGIN
    DELETE FROM CAR_TBL WHERE CAR_ID = THIS_CAR_ID;
    COMMIT;
END;
/
--CREATE PROCEDURE UPDATECAR_OWNER
--(THIS_CAR_ID NUMBER, USER_ID NUMBER)
--AS
--BEGIN
--    UPDATE CAR_TBL
--    SET CAR_OWNER = USER_ID
--    WHERE CAR_ID = THIS_CAR_ID;
--END;
--/

CREATE OR REPLACE PROCEDURE INSERTOFFER
(CAR_ID NUMBER, USER_ID NUMBER,  OFFER_DOWNPAYMENT NUMBER, OFFER_TERMLOANLENGTH NUMBER)
AS
BEGIN
    INSERT INTO OFFER_TBL VALUES(OFFER_SEQ.NEXTVAL, CAR_ID, USER_ID, OFFER_DOWNPAYMENT, OFFER_TERMLOANLENGTH, 'Pending');
    COMMIT;
END;
/
CREATE OR REPLACE PROCEDURE UPDATEOFFER_STATUS
(THIS_OFFER_ID NUMBER,THIS_CAR_ID NUMBER,THIS_USER_ID NUMBER,DOWNPAYMENT NUMBER, NEW_STATUS VARCHAR2)
AS
BEGIN
    IF NEW_STATUS = 'Accepted' THEN 
        UPDATE OFFER_TBL SET OFFER_STATUS = 'Declined'  WHERE CAR_ID = THIS_CAR_ID;
        
        UPDATE OFFER_TBL SET OFFER_STATUS = NEW_STATUS WHERE OFFER_ID = THIS_OFFER_ID;
        
        UPDATE CAR_TBL SET CAR_OWNER = THIS_USER_ID WHERE CAR_ID = THIS_CAR_ID;
        
        INSERT INTO CONTRACT_TBL VALUES(CONTRACT_SEQ.NEXTVAL,THIS_OFFER_ID);
        
        INSERT INTO PAYMENT_TBL VALUES(PAYMENT_SEQ.NEXTVAL,DOWNPAYMENT,CONTRACT_SEQ.CURRVAL);
        COMMIT;
    ELSE
        UPDATE OFFER_TBL
        SET OFFER_STATUS = NEW_STATUS
        WHERE OFFER_ID = THIS_OFFER_ID;
    END IF;
END;
/
--CREATE OR REPLACE PROCEDURE INSERTCONTRACT
--(OFFER_ID NUMBER, DOWNPAYMENT NUMBER)
--AS
--BEGIN
--    INSERT INTO CONTRACT_TBL VALUES(CONTRACT_SEQ.NEXTVAL,OFFER_ID);
--    INSERT INTO PAYMENT_TBL VALUES(PAYMENT_SEQ.NEXTVAL,DOWNPAYMENT,CONTRACT_SEQ.CURRVAL);
--    COMMIT;
--END;
--/
--CREATE OR REPLACE PROCEDURE CONTRACT
--SELECT * FROM CONTRACT_TBL C
--INNER JOIN OFFER_TBL O
--ON C.OFFER_ID = O.OFFER_ID;

CREATE OR REPLACE PROCEDURE INSERTPAYMENT
(PAYMENT_VALUE NUMBER, CONTRACT_ID NUMBER)
AS
BEGIN
    INSERT INTO PAYMENT_TBL VALUES(PAYMENT_SEQ.NEXTVAL,PAYMENT_VALUE,CONTRACT_ID);
    COMMIT;
END;
/

-----------------------------------------------------------
--Starting Data
TRUNCATE TABLE USER_TBL;
DROP SEQUENCE USER_SEQ;
CREATE SEQUENCE USER_SEQ
        INCREMENT BY 1 MAXVALUE 5000 CYCLE;
INSERT INTO USER_TBL VALUES(0,'LOT','LOT','LOT');
EXECUTE INSERTUSER('Barry','password');
EXECUTE INSERTUSER('Dolores','password');

TRUNCATE TABLE CAR_TBL;
DROP SEQUENCE CAR_SEQ;
CREATE SEQUENCE CAR_SEQ
        INCREMENT BY 1 MAXVALUE 5000 CYCLE;
EXECUTE INSERTCAR('Truck',1985,'blue',2500.45);
EXECUTE INSERTCAR('Car',2010,'white',10000.99);
EXECUTE INSERTCAR('SUV',2014,'grey',15000.25);
EXECUTE INSERTCAR('Van',1995,'brown',5000.95);
EXECUTE INSERTCAR('Bus',2004,'yellow',19000.15);

TRUNCATE TABLE OFFER_TBL;
DROP SEQUENCE OFFER_SEQ;
CREATE SEQUENCE OFFER_SEQ
  INCREMENT BY 1 MAXVALUE 5000 CYCLE;
  --CAR_ID , USER_ID ,  OFFER_DOWNPAYMENT , OFFER_TERMLOANLENGTH 
EXECUTE INSERTOFFER(1,1,650.45,12); 
EXECUTE INSERTOFFER(1,2,2000.25,76); 
EXECUTE INSERTOFFER(2,2,100.25,76); 

TRUNCATE TABLE CONTRACT_TBL;
DROP SEQUENCE CONTRACT_SEQ;
CREATE SEQUENCE CONTRACT_SEQ
  INCREMENT BY 1 MAXVALUE 5000 CYCLE;
  
TRUNCATE TABLE PAYMENT_TBL;
DROP SEQUENCE PAYMENT_SEQ;
CREATE SEQUENCE PAYMENT_SEQ
  INCREMENT BY 1 MAXVALUE 5000 CYCLE;

--THIS_OFFER_ID ,THIS_CAR_ID ,THIS_USER_ID ,DOWNPAYMENT , NEW_STATUS 
EXECUTE UPDATEOFFER_STATUS(1,1,1,650.50,'Accepted');
EXECUTE UPDATEOFFER_STATUS(3,2,2,100.25,'Accepted');
--PAYMENT_VALUE , CONTRACT_ID 
EXECUTE INSERTPAYMENT(100,1);

-----------------------------------------------------------
--CONSTRAINTS
--ALTER TABLE PAYMENT_TBL
--DROP CONSTRAINT FK_PAYMENTCONTRACTID;

ALTER TABLE OFFER_TBL
ADD CONSTRAINT FK_OFFERCARID
FOREIGN KEY (CAR_ID) REFERENCES CAR_TBL(CAR_ID);

ALTER TABLE OFFER_TBL
ADD CONSTRAINT FK_OFFERUSERID
FOREIGN KEY (USER_ID) REFERENCES USER_TBL(USER_ID);

ALTER TABLE CAR_TBL
ADD CONSTRAINT FK_CAROWNERID
FOREIGN KEY (CAR_OWNER) REFERENCES USER_TBL(USER_ID);

--trying to get a 1:1 relationship.
ALTER TABLE CONTRACT_TBL
ADD (CONSTRAINT FK_CONTRACTOFFERID
FOREIGN KEY (OFFER_ID) REFERENCES OFFER_TBL(OFFER_ID),
CONSTRAINT UNIQ_CONTRACTOFFER UNIQUE(OFFER_ID));

ALTER TABLE PAYMENT_TBL
ADD CONSTRAINT FK_PAYMENTCONTRACTID
FOREIGN KEY (CONTRACT_ID) REFERENCES CONTRACT_TBL(CONTRACT_ID);
