export interface Rform {
  id: number;
  empID: number;
  status: string;
  isUrgent: string;
  supApr: string;
  supSubDate: string;
  headApr: string;
  headSubDate: string;
  coorApr: string;
  coorSubDate: string;
  isAltered: string;
  rejectMessage: string;
  formSubDate: string;
  startDate: string;
  startTime: string;
  location: string;
  cost: number;
  pendingRe: number;
  description: string;
  justification: string;
  gradeFormatID: number;
  eventType: string;
  onSubmit: string;
  finalGrade: number;
  gradeApr: string;
  finalPres: string;
  presApr: string;
}
